services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradeportal_app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SEVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JACKSON_TIME_ZONE: ${JACKSON_TIME_ZONE}
    depends_on:
      - db

  db:
    image: postgres:17 # Phiên bản PostgreSQL là 17, đồng bộ với thông tin của bạn
    container_name: gradeportal_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: HCMUT_Grade_Portal_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
