services:
  app:
    image: trandaiviet/gradeportal-app:latest
    container_name: gradeportal_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: gradeportal_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: HCMUT_Grade_Portal_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
