spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  # Cấu hình server (có thể bỏ qua nếu không cần)
  # server:
  #   port: ${SERVER_PORT}
  #   servlet:
  #     context-path: ${SERVER_CONTEXT_PATH}

  # Cấu hình dữ liệu
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      maximum-pool-size: 10

  # Cấu hình Hibernate và JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

  # Cấu hình thư mục cho file static
  thymeleaf:
    cache: false

  # Cấu hình bảo mật OAuth2 Google và JWT
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

  # Cấu hình thời gian
  jackson:
    time-zone: ${JACKSON_TIME_ZONE}
